# Generated by Django 2.2.13 on 2021-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postCreator', models.CharField(max_length=200)),
                ('projectTitle', models.CharField(max_length=200)),
                ('projectDescriptions', models.TextField()),
                ('projectVideoUrl', models.TextField(blank=True)),
                ('projectGithubUrl', models.TextField(blank=True)),
                ('ProjectImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('projectViews', models.IntegerField(default=0)),
                ('projectTimeDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
