# Generated by Django 2.2.13 on 2021-03-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ProjectImage',
            new_name='projectImage',
        ),
    ]
