# Generated by Django 2.2.13 on 2021-03-12 15:28

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210312_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectVideoUrl',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
