# Generated by Django 2.2.13 on 2021-03-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210312_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectVideoUrl',
            field=models.TextField(blank=True),
        ),
    ]
