# Generated by Django 2.2.13 on 2021-03-14 03:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210314_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectBody',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
