# Generated by Django 3.1.7 on 2021-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210325_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectGithubUrl',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectImage',
        ),
        migrations.AddField(
            model_name='project',
            name='projectPrority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
