# Generated by Django 3.1.7 on 2021-04-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_achievment_certificate_education_exprience_myself_researchpaper_skill_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievment',
            new_name='Achievement',
        ),
    ]
