# Generated by Django 3.1.7 on 2021-04-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210421_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
